import { Fragment } from "react";
import { Flex } from "@chakra-ui/react";
import { GetStaticProps } from "next";
import Head from "next/head";

import { Aside } from "@/components/Aside";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { Navbar } from "@/components/Navbar";
import { ProjectsList } from "@/components/ProjectsList";
import { getPrismicClient } from "@/services/prismic";
import { formatProjects } from "@/utils/formatPrismic";

type Project = {
  title: string;
  description: string;
  slug: string;
};

interface HomeProps {
  projects: Project[];
}

export default function Home({ projects }: HomeProps) {
  return (
    <Fragment>
      <Head>
        <title>Mário Santos - Desenvolvedor FullStack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Header />

      <Flex
        maxW="container.lg"
        mx="auto"
        my={12}
        gap={[12, 12, 4]}
        flexDir={["column", "column", "row"]}
      >
        <ProjectsList projects={projects} />
        <Aside />
      </Flex>

      <Footer />
    </Fragment>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const prismic = getPrismicClient({});
  const { results } = await prismic.getByType("projects", {
    pageSize: 5,
  });

  return {
    props: {
      projects: formatProjects(results),
    },
    revalidate: 60 * 60 * 4, // 4 hours
  };
};
