import { Fragment } from "react";
import { Container, Flex } from "@chakra-ui/react";
import { GetStaticProps } from "next";
import Head from "next/head";

import { Aside } from "@/components/Aside";
import { Footer } from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import { ProjectsList } from "@/components/ProjectsList";
import { Memoji } from "@/components/Memoji";
import { getPrismicClient } from "@/services/prismic";
import { formatProjects } from "@/utils/formatPrismic";

type Project = {
  title: string;
  description: string;
  slug: string;
};
interface ProjectsProps {
  projects: Project[];
  nextPage?: string;
}

export default function Projects({ projects }: ProjectsProps) {
  return (
    <Flex flexDir="column" minH="100vh">
      <Head>
        <title>Mário Santos - Projetos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Container as={Flex} maxW="container.lg" w="full">
        <Memoji
          image="/images/memoji-writting.png"
          maxW={{ base: "100%", md: "20%" }}
        />
      </Container>

      <Flex
        maxW="container.lg"
        mx="auto"
        my={12}
        gap={[12, 12, 4]}
        flexDir={["column", "column", "row"]}
        flex={1}
      >
        <ProjectsList title="Meus Projetos" projects={projects} />
        <Aside />
      </Flex>

      <Footer />
    </Flex>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const prismic = getPrismicClient({});
  const { next_page, results } = await prismic.getByType("projects", {
    pageSize: 5,
  });

  return {
    props: {
      projects: formatProjects(results),
      nextPage: next_page ?? null,
    },
    revalidate: 60 * 60 * 4, // 4 hours
  };
};
